
name: Building Satochip-Utils binaries


on:
  push:
    tags: '*'
    branches: [ master, dev, test_*]


jobs:

  build_win:

    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        architecture: 'x64'
    - name: Build bin package
      run: |
        cd package
        ./Build-Windows.bat
    - name: 'Archive windows bin (unsigned!)'
      uses: actions/upload-artifact@v4
      with:
        name: windist-unsigned
        path: |
          dist/


  build_linux:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
    - name: Prepare Linux system
      run: |
        sudo apt update
        sudo apt install -y xvfb curl libnotify4 libgtk-3-0 libsdl2-2.0-0 libsdl2-dev libpcsclite-dev
        sudo apt install -y python3-venv python3-pip python3-tk python3-pyscard
    - name: Build bin package
      run: |
        xvfb-run --server-args='-screen 0, 1024x768x24' bash package/Build-Linux.sh
    - name: 'Archive linux bin (unsigned!)'
      uses: actions/upload-artifact@v4
      with:
        name: nuxdist-unsigned
        path: |
          dist/

  build_linux_legacy:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v4
    - name: Prepare Linux system
      run: |
        sudo apt update
        sudo apt install -y xvfb curl libnotify4 libgtk-3-0 libsdl2-2.0-0 libsdl2-dev libpcsclite-dev
        sudo apt install -y python3-venv python3-pip python3-tk python3-pyscard
    - name: Build bin package
      run: |
        xvfb-run --server-args='-screen 0, 1024x768x24' bash package/Build-Linux-legacy.sh
    - name: 'Archive linux bin (unsigned!)'
      uses: actions/upload-artifact@v4
      with:
        name: nuxdist-legacy-unsigned
        path: |
          dist/

  build_mac_x86-64:

    runs-on: macos-12

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: test import tkinter
      run: python3 -c 'import tkinter'
    - name: Install dependencies
      run: |
        brew install python-tk
    - name: Build bin package
      run: |
        chmod +x ./package/Build-Mac.sh
        ./package/Build-Mac.sh
        chmod +x ./dist/satochip_utils.app/Contents/MacOS/satochip_utils
    - name: 'Archive MacOS bin (unsigned!)'
      uses: actions/upload-artifact@v4
      with:
        name: macdist-x86_64-unsigned
        path: |
          dist/

  build_mac_arm64:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: test import tkinter
        run: | 
          python3 -c 'import tkinter'
      - name: Install dependencies
        run: |
          brew install python-tk
      - name: Build bin package
        run: |
          chmod +x ./package/Build-Mac.sh
          ./package/Build-Mac.sh
      - name: 'Archive MacOS bin (unsigned!)'
        uses: actions/upload-artifact@v4
        with:
          name: macdist-arm64-unsigned
          path: |
            dist/